# This workflow will update the timezone data from the official database and can only be triggered manually
# requires to set environment variable tzVersion

name: update tz data

on:
  workflow_dispatch

jobs:
  fetch-build-and-update:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v3
      - run: bash ${GITHUB_WORKSPACE}/update-tzdata.sh ${{secrets.tzVersion}}
