# This workflow will update the timezone data from the official database and can only be triggered manually
# requires to set environment variable tzVersion

name: update tz data

on:
  workflow_dispatch:
    branches: [dev]

jobs:
  fetch-build-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bash  update-tzdata.sh ${{secrets.tzVersion}}
