# This workflow will update the timezone data from the official database and can only be triggered manually
# requires to set environment variable tzVersion

name: update tz data

on: workflow_dispatch

jobs:
  fetch-build-and-update:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: update
        run: bash ${GITHUB_WORKSPACE}/update-tzdata.sh ${{secrets.tzVersion}}
      - name: commit
        run: |
          git config --global user.name 'Jens Kuerschner' 
          git config --global user.email 'mail@jenskuerschner.de'
          git add -A
          git commit -m '[automated commit] tz data update'
          git push
